# prompts/__init__.py
from .inference import INFERENCE_PROMPT
from .mechanics import MECHANICS_PROMPT
from .narration import NARRATION_PROMPT, NPC_STATE_UPDATE_PROMPT, DIALOGUE_GENERATION_PROMPT
from .world_building import LOCATION_GENERATION_PROMPT, WORLD_EVENT_PROMPT
from .quest import QUEST_GENERATION_PROMPT

__all__ = [
    "INFERENCE_PROMPT",
    "MECHANICS_PROMPT",
    "NARRATION_PROMPT",
    "NPC_STATE_UPDATE_PROMPT",
    "DIALOGUE_GENERATION_PROMPT",
    "LOCATION_GENERATION_PROMPT",
    "WORLD_EVENT_PROMPT",
    "QUEST_GENERATION_PROMPT"
]